package ru.emplosecrets.web.entity;
// Generated Apr 16, 2018 10:01:01 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

    private Long comId;
    private Employer employer;
    private User user;
    private Date date;
    private String text;

    public Comment() {
    }

    public Comment(Employer employer, User user, Date date, String text) {
        this.employer = employer;
        this.user = user;
        this.date = date;
        this.text = text;
    }

    public Long getComId() {
        return this.comId;
    }

    public void setComId(Long comId) {
        this.comId = comId;
    }

    public Employer getEmployer() {
        return this.employer;
    }

    public void setEmployer(Employer employer) {
        this.employer = employer;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Comment getComment() {
        Comment comment = new Comment();
        comment.setEmployer(getEmployer());
        comment.setUser(getUser());
        comment.setDate(getDate());
        comment.setText(getText());
        return comment;
    }

}
