package ru.emplosecrets.web.entity;
// Generated Apr 16, 2018 10:01:01 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Industry generated by hbm2java
 */
public class Industry implements java.io.Serializable {

    private Long indId;
    private String name_ru;
    private String name_en;
    private Set employers = new HashSet(0);

    public Industry() {
    }

    public Industry(String name_ru, String name_en) {
        this.name_ru = name_ru;
        this.name_en = name_en;
    }

    public Industry(String name_ru, String name_en, Set employers) {
        this.name_ru = name_ru;
        this.name_en = name_en;
        this.employers = employers;
    }

    public Long getIndId() {
        return this.indId;
    }

    public void setIndId(Long indId) {
        this.indId = indId;
    }

    public String getName_ru() {
        return this.name_ru;
    }

    public void setName_ru(String name_ru) {
        this.name_ru = name_ru;
    }

    public String getName_en() {
        return name_en;
    }

    public void setName_en(String name_en) {
        this.name_en = name_en;
    }

    public Set getEmployers() {
        return this.employers;
    }

    public void setEmployers(Set employers) {
        this.employers = employers;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.indId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Industry other = (Industry) obj;
        if (!Objects.equals(this.indId, other.indId)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return name_ru;
    }

}
